'use strict';
const $=id=>document.getElementById(id), memoryKey='chocolala.transfer.branch-options.v1', formsKey='chocolala.transfer.forms.v1';
let routes=[], selectedRoute=null, sourceBranches=[], destinationBranches=[], chosenFrom='', chosenTo='', rowSequence=0, signature=[], drawing=null, pointer=null, saveTimer, loading=false, formId=crypto.randomUUID(), suffix='', savedForms=[], dirty=false;
let products=new Map(),productUpcs=new Map(),productUoms=[],productsReady=false;
const sorted=values=>[...new Set(values)].sort((a,b)=>a.localeCompare(b));
function fitTextarea(input){input.style.height='auto';input.style.height=Math.max(40,input.scrollHeight+2)+'px';}
window.addEventListener('resize',()=>document.querySelectorAll('.entry-table textarea').forEach(fitTextarea));
function status(message){$('action-status').hidden=false;$('action-status').textContent=message;}
function remember(){try{localStorage.setItem(memoryKey,JSON.stringify({country:$('country').value,from:chosenFrom,to:chosenTo,code:selectedRoute?.code||''}));}catch(_){}}
function checkBarcode(input,committed){
 const value=input.value,valid=InventoryProducts.resolveBarcode(value,productUpcs);
 const message=!value||valid?'':/\D/.test(value)?'Use digits only.':committed||value.length>=13?'Enter a 13-digit barcode starting with 3 or 4, or a UPC from the product list.':'';
 input.setCustomValidity(message);input.setAttribute('aria-invalid',String(!!message));
 let hint=input.parentElement.querySelector('.field-error');if(!hint){hint=document.createElement('span');hint.className='field-error';hint.id='barcode-error-'+(++errorSequence);hint.setAttribute('aria-live','polite');input.parentElement.append(hint);input.setAttribute('aria-describedby',hint.id);}hint.textContent=message;hint.hidden=!message;
 return !message;
}
let errorSequence=0;const sessionVersions=new Map();
function nextVersion(reference){
 let counters={};try{counters=JSON.parse(localStorage.getItem('chocolala.transfer.version-counters.v1')||'{}');}catch(_){}
 return Math.max(sessionVersions.get(reference)||0,Number(counters[reference])||0,...savedForms.filter(s=>s.reference===reference).map(s=>Number(s.version)||0))+1;
}
function saveDownload(data){
 sessionVersions.set(data.reference,data.version);
 const next=[data,...savedForms.filter(s=>s.id!==formId)].slice(0,10);
 try{localStorage.setItem(formsKey,JSON.stringify(next));let counters={};try{counters=JSON.parse(localStorage.getItem('chocolala.transfer.version-counters.v1')||'{}');}catch(_){}counters[data.reference]=data.version;localStorage.setItem('chocolala.transfer.version-counters.v1',JSON.stringify(counters));savedForms=next;dirty=false;renderSaved();$('save-status').textContent='Version '+data.version+' saved in this browser.';}catch(_){$('save-status').textContent='PDF downloaded, but browser storage could not save this version.';}
}
function search(input,list,getValues,choose){
 let index=-1;
 function close(){list.hidden=true;input.setAttribute('aria-expanded','false');input.removeAttribute('aria-activedescendant');index=-1;}
 function render(){const values=getValues().filter(v=>TransferRules.branchMatches(v,input.value));list.replaceChildren();index=-1;input.removeAttribute('aria-activedescendant');values.forEach((value,i)=>{const b=document.createElement('button');b.type='button';b.role='option';b.tabIndex=-1;b.id=input.id+'-result-'+i;b.textContent=value;b.setAttribute('aria-selected','false');b.addEventListener('mousedown',e=>e.preventDefault());b.addEventListener('click',()=>{input.value=value;choose(value);input.focus();close();remember();scheduleSave();});list.append(b);});if(!values.length){const p=document.createElement('p');p.textContent='No matches';list.append(p);}list.hidden=false;input.setAttribute('aria-expanded','true');}
 input.addEventListener('focus',render);input.addEventListener('blur',close);input.addEventListener('input',()=>{choose(getValues().includes(input.value)?input.value:'',true);render();remember();scheduleSave();});
 input.addEventListener('keydown',e=>{if(e.key==='Escape')return close();if(['ArrowDown','ArrowUp'].includes(e.key)){e.preventDefault();if(list.hidden)render();const choices=[...list.querySelectorAll('[role=option]')];if(!choices.length)return;index=(index+(e.key==='ArrowDown'?1:-1)+choices.length)%choices.length;choices.forEach((b,i)=>b.setAttribute('aria-selected',String(i===index)));input.setAttribute('aria-activedescendant',choices[index].id);choices[index].scrollIntoView({block:'nearest'});}else if(e.key==='Enter'&&!list.hidden){e.preventDefault();const choices=[...list.querySelectorAll('[role=option]')],b=choices[index]||(choices.length===1?choices[0]:null);if(b){input.value=b.textContent;choose(b.textContent);close();remember();scheduleSave();}}});return close;
}
function chooseRoute(route){selectedRoute=route;const d=route?TransferRules.transferDetails(route):null;$('route-details').hidden=!route||!!route.detailsMissing;$('supplier-details').hidden=!d||d.internal||!!route?.detailsMissing;$('type').value=d?.type||'';$('code-label').dataset.english=d?.codeLabel||'Supplier code / TR code';$('code-label').textContent=InventoryI18n.header($('code-label').dataset.english);$('supplier-code').closest('label').hidden=!!route?.detailsMissing;$('supplier-code').value=d?.code||'';$('reference').value=(d?.prefix||'TR')+suffix;if(route)for(const [id,value]of[['from-entity',route.fromEntity],['to-entity',route.toEntity],['from-warehouse',route.fromWarehouse],['to-warehouse',route.toWarehouse],['supplier',d.supplier]])$(id).textContent=value;$('print-button').disabled=$('print-bottom').disabled=!route;InventoryI18n.apply(document.querySelector('.automatic-panel'));}
function setDestination(code=''){
 const matches=routes.filter(r=>r.country===$('country').value&&r.from===chosenFrom&&r.to===chosenTo&&r.criteria===chosenFrom+chosenTo);
 $('route-choice-wrap').hidden=matches.length<=1;$('route-choice').replaceChildren(new Option('Select warehouse route',''));
 matches.forEach(r=>$('route-choice').add(new Option(r.code+' · '+r.fromWarehouse+' → '+r.toWarehouse,String(routes.indexOf(r)))));
 const selected=matches.find(r=>r.code===code)||(matches.length===1?matches[0]:null)||(!matches.length?TransferRules.unconfiguredRoute(routes,$('country').value,chosenFrom,chosenTo):null);
 if(selected&&!selected.unconfigured)$('route-choice').value=String(routes.indexOf(selected));chooseRoute(selected);
 const notice=$('route-notice');notice.hidden=true;
 if(chosenFrom&&chosenTo&&chosenFrom===chosenTo){notice.textContent='Choose two different branches.';notice.hidden=false;}
}

function setSource(value,preserve=false){chosenFrom=sourceBranches.includes(value)?value:'';if(!preserve)$('from').value=chosenFrom;$('from').setCustomValidity(chosenFrom?'':'Choose a source branch from the results.');destinationBranches=[...sourceBranches];chosenTo=destinationBranches.includes(chosenTo)?chosenTo:'';$('to').value=chosenTo;$('to').disabled=!destinationBranches.length;$('to').setCustomValidity(chosenTo?'':'Choose a destination branch from the results.');closeTo();setDestination();}

function setCountry(){chosenTo='';sourceBranches=sorted(routes.filter(r=>r.country===$('country').value).flatMap(r=>[r.from,r.to]));$('from').disabled=!sourceBranches.length;setSource('');closeFrom();}
const closeFrom=search($('from'),$('from-results'),()=>sourceBranches,setSource),closeTo=search($('to'),$('to-results'),()=>destinationBranches,value=>{chosenTo=value;$('to').setCustomValidity(value?'':'Choose a destination branch from the results.');setDestination();});
$('country').addEventListener('change',()=>{setCountry();remember();scheduleSave();});$('route-choice').addEventListener('change',()=>{chooseRoute($('route-choice').value===''?null:routes[Number($('route-choice').value)]);remember();scheduleSave();});
function count(){[...$('item-rows').rows].forEach((row,i)=>{row.cells[0].textContent=String(i+1);row.querySelector('button').setAttribute('aria-label','Remove item '+(i+1));});const n=[...$('item-rows').rows].filter(rowHasData).length;$('item-count').textContent=n+' item'+(n===1?'':'s');}
function applyBarcode(row,defaults=true){
 const values=InventoryProducts.resolveBarcode(row.querySelector('[name=barcode]').value,productUpcs),code=row.querySelector('[name=code]'),batch=row.querySelector('[name=batch]');
 code.readOnly=!!values;code.tabIndex=values?-1:0;
 if(values){code.value=values.code;code.setCustomValidity('');if(values.kind==='4'||defaults)batch.value=values.batch;batch.setCustomValidity('');}
 if(values&&defaults){row.querySelector('[name=uom]').value='Pieces';row.querySelector('[name=uom]').setCustomValidity('');row.querySelector('[name=quantity]').value='1';}
 applyProduct(row,defaults);
}
function rowValues(row){const values=Object.fromEntries([...row.querySelectorAll('input,textarea')].map(input=>[input.name,input.value.trim()])),parsed=InventoryProducts.resolveBarcode(values.barcode,productUpcs);return {...values,barcode4:parsed?.kind==='4'?values.barcode:'',barcode3:parsed&&parsed.kind!=='4'?values.barcode:''};}
function rowHasData(row){return Object.values(rowValues(row)).some(Boolean);}
function ensureNextRow(){const last=$('item-rows').rows[$('item-rows').rows.length-1];if(!last||rowHasData(last))addRow();count();}
function applyProduct(row,fill=true){
 const code=row.querySelector('[name=code]').value.trim(),product=products.get(code),batch=row.querySelector('[name=batch]'),parsed=InventoryProducts.resolveBarcode(row.querySelector('[name=barcode]').value,productUpcs),four=parsed?.kind==='4',three=parsed?.kind==='3';
 if(fill&&(row.dataset.productCode!==code||product&&row.dataset.catalogFilled!=='true')){for(const key of ['name','uom']){const field=row.querySelector('[name='+key+']');if(product)field.value=product[key];else if(row.dataset.catalogFilled==='true')field.value='';field.setCustomValidity('');}row.dataset.catalogFilled=String(!!product);}
 row.dataset.productCode=code;batch.required=!!product?.batched;
 if(product){batch.readOnly=!product.batched||!!four;if(!product.batched){batch.value='';batch.setCustomValidity('');}}
 else {batch.readOnly=!!four||!!three;}
 batch.tabIndex=batch.readOnly?-1:0;batch.setAttribute('aria-required',String(batch.required));batch.title=product?(product.batched?'Batch is required for this product.':'This product does not use batches.'):'Batch';fitTextarea(batch);fitTextarea(row.querySelector('[name=name]'));
}
function addRow(values={}){const row=$('item-rows').insertRow(),n=++rowSequence;row.insertCell();for(const [key,label]of[['barcode','Barcode'],['code','Item code'],['batch','Batch'],['name','Item name'],['uom','UOM'],['quantity','Quantity']]){const input=document.createElement(['name','batch'].includes(key)?'textarea':'input');input.name=key;if(input.tagName==='INPUT')input.type=key==='quantity'?'number':'text';else input.rows=2;input.setAttribute('aria-label',label+' for item '+n);input.required=['code','name','uom','quantity'].includes(key);input.maxLength=key==='name'?150:80;if(key==='quantity'){input.min='.001';input.step='.001';input.placeholder='0.000';}if(['code','barcode'].includes(key)){input.inputMode='numeric';if(key==='code'){input.minLength=6;input.maxLength=6;input.pattern='[0-9]{6}';input.title='Enter exactly 6 digits.';}else{input.pattern='[0-9]+';input.title='13 digits starting with 3 or 4, or a matching product UPC.';}}if(key==='batch'){input.minLength=6;input.maxLength=17;input.pattern='.{6,17}';}if(key==='uom'){input.setAttribute('list','uom-options');input.placeholder='Type UOM';}input.value=(key==='barcode'?(values.barcode||values.barcode4||values.barcode3):values[key])||'';const cell=row.insertCell();cell.dataset.label=label;cell.append(input);if(key==='code')input.addEventListener('input',()=>{applyProduct(row);ensureNextRow();});if(key==='quantity')input.addEventListener('keydown',e=>{if(e.key==='Enter'){e.preventDefault();const invalid=[...row.querySelectorAll('input,textarea')].find(field=>!field.checkValidity());if(invalid){invalid.reportValidity();return;}ensureNextRow();(row.nextElementSibling||addRow()).querySelector('input').focus();scheduleSave();}});if(key==='barcode'){input.addEventListener('input',()=>{applyBarcode(row);checkBarcode(input,false);ensureNextRow();});input.addEventListener('blur',()=>checkBarcode(input,true));input.addEventListener('keydown',e=>{if(['Enter','Tab'].includes(e.key)){if(!checkBarcode(input,true)){e.preventDefault();input.reportValidity();return;}if(e.key==='Enter'||(e.key==='Tab'&&InventoryProducts.resolveBarcode(input.value,productUpcs))){e.preventDefault();row.querySelector(InventoryProducts.resolveBarcode(input.value,productUpcs)?'[name=name]':'[name=code]').focus();}}});}}
 const b=document.createElement('button');b.type='button';b.className='remove-row';b.textContent='×';b.addEventListener('click',()=>{if($('item-rows').rows.length===1)row.querySelectorAll('input,textarea').forEach(i=>{i.value='';i.readOnly=false;i.tabIndex=0;i.setCustomValidity('');});else row.remove();if(row.isConnected){checkBarcode(row.querySelector('[name=barcode]'),false);applyBarcode(row,false);row.querySelectorAll('textarea').forEach(fitTextarea);}ensureNextRow();scheduleSave();});const removeCell=row.insertCell();removeCell.className='remove-cell';removeCell.append(b);applyBarcode(row,false);row.querySelectorAll('textarea').forEach(fitTextarea);count();InventoryI18n.apply(row);return row;}
const uoms=document.createElement('datalist');uoms.id='uom-options';productUoms.forEach(v=>uoms.append(new Option(v,v)));document.body.append(uoms);
for(const id of ['add-row','add-row-bottom'])$(id).addEventListener('click',()=>{addRow().querySelector('input').focus();scheduleSave();});
$('transfer-form').addEventListener('submit',e=>e.preventDefault());$('transfer-form').addEventListener('input',e=>{if(e.target.tagName==='TEXTAREA')fitTextarea(e.target);if(e.target.name==='uom')e.target.setCustomValidity(productUoms.includes(e.target.value)?'':'Choose a UOM from the list.');else if(!['from','to'].includes(e.target.id)&&e.target.name!=='barcode')e.target.setCustomValidity('');if(e.target.closest('#item-rows'))ensureNextRow();scheduleSave();});$('reason').addEventListener('change',scheduleSave);
function newIdentity(){dirty=false;const now=new Date(),parts=new Intl.DateTimeFormat('en-GB',{timeZone:'Asia/Dubai',day:'2-digit',month:'2-digit',year:'2-digit',hour:'2-digit',minute:'2-digit',second:'2-digit',hourCycle:'h23'}).formatToParts(now),p=type=>parts.find(v=>v.type===type).value;suffix=' '+p('day')+p('month')+p('year')+'-'+p('hour')+p('minute')+p('second');$('date').value=new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Dubai',year:'numeric',month:'2-digit',day:'2-digit'}).format(now);formId=crypto.randomUUID();chooseRoute(selectedRoute);}
function snapshot(){return{language:InventoryI18n.language(),id:formId,updated:new Date().toISOString(),country:$('country').value,from:chosenFrom,to:chosenTo,routeCode:selectedRoute?.code||'',route:selectedRoute,details:selectedRoute?TransferRules.transferDetails(selectedRoute):null,date:$('date').value,reference:$('reference').value,referenceSuffix:suffix,reason:$('reason').value,prepared:$('prepared').value,received:$('received').value,signature,items:[...$('item-rows').rows].filter(rowHasData).map(rowValues)};}
function renderSaved(){$('saved-forms').replaceChildren();if(!savedForms.length){const p=document.createElement('p');p.className='field-help';p.textContent='Your forms will appear here as you work.';$('saved-forms').append(p);}savedForms.forEach(s=>{const b=document.createElement('button');b.type='button';b.className='saved-form'+(s.id===formId?' selected':'');const title=document.createElement('strong');title.textContent=s.reference+(s.version?' · v'+s.version:' · Draft');const branches=document.createElement('span');branches.textContent=(s.from||'Source pending')+' → '+(s.to||'Destination pending');const date=document.createElement('small');date.textContent=s.date+' · '+s.items.length+' item(s)';b.append(title,branches,date);b.addEventListener('click',()=>{saveCurrent();restore(s);});$('saved-forms').append(b);});}
function saveCurrent(){clearTimeout(saveTimer);if(loading||!routes.length||!dirty)return;const data=snapshot();if(!data.from&&!data.items.some(i=>Object.values(i).some(Boolean)))return;const next=[data,...savedForms.filter(s=>s.id!==formId||s.version)].slice(0,10);try{localStorage.setItem(formsKey,JSON.stringify(next));savedForms=next;dirty=false;renderSaved();$('save-status').textContent='Saved in this browser.';}catch(_){$('save-status').textContent='Could not save. Browser storage may be disabled or full. Download your PDF to keep it.';}}
function scheduleSave(){if(!loading){dirty=true;clearTimeout(saveTimer);saveTimer=setTimeout(saveCurrent,500);}}
function restore(s){clearTimeout(saveTimer);loading=true;dirty=false;try{formId=s.version?crypto.randomUUID():s.id;suffix=s.referenceSuffix;$('date').value=s.date;$('country').value=s.country;setCountry();setSource(s.from);chosenTo=destinationBranches.includes(s.to)?s.to:'';$('to').value=chosenTo;$('to').setCustomValidity(chosenTo?'':'Choose a destination branch.');setDestination(s.routeCode);$('reason').value=['Shop Request','Customer Order'].includes(s.reason)?s.reason:'Shop Request';$('prepared').value=s.prepared||'';$('received').value=s.received||'';$('item-rows').replaceChildren();rowSequence=0;(s.items.length?s.items:[{}]).forEach(addRow);ensureNextRow();signature=Array.isArray(s.signature)?structuredClone(s.signature):[];redrawSignature();remember();renderSaved();if(!selectedRoute)status('This saved route is no longer available. Choose a current route.');}finally{loading=false;}}
$('new-form').addEventListener('click',()=>{saveCurrent();loading=true;newIdentity();$('reason').value='Shop Request';$('prepared').value='';$('received').value='';$('item-rows').replaceChildren();rowSequence=0;addRow();signature=[];redrawSignature();$('action-status').hidden=true;loading=false;renderSaved();});window.addEventListener('pagehide',saveCurrent);
const canvas=$('signature'),context=canvas.getContext('2d');
function redrawSignature(){context.clearRect(0,0,canvas.width,canvas.height);context.strokeStyle='#10485b';context.lineWidth=4;context.lineCap='round';context.lineJoin='round';for(const stroke of signature){if(!stroke.length)continue;context.beginPath();context.moveTo(stroke[0][0]*canvas.width,stroke[0][1]*canvas.height);for(const p of stroke.slice(1))context.lineTo(p[0]*canvas.width,p[1]*canvas.height);context.stroke();}}
function point(e){const r=canvas.getBoundingClientRect();return[Math.max(0,Math.min(1,(e.clientX-r.left)/r.width)),Math.max(0,Math.min(1,(e.clientY-r.top)/r.height))];}
canvas.addEventListener('pointerdown',e=>{if(pointer!==null)return;e.preventDefault();pointer=e.pointerId;canvas.setPointerCapture(pointer);drawing=[point(e)];signature.push(drawing);canvas.classList.remove('signature-missing');$('signature-error').hidden=true;redrawSignature();});canvas.addEventListener('pointermove',e=>{if(e.pointerId===pointer&&drawing){drawing.push(point(e));redrawSignature();}});function endSignature(e){if(e.pointerId===pointer){if(drawing?.length===1)drawing.push([...drawing[0]]);pointer=null;drawing=null;scheduleSave();}}for(const name of ['pointerup','pointercancel','lostpointercapture'])canvas.addEventListener(name,endSignature);$('clear-signature').addEventListener('click',()=>{signature=[];redrawSignature();$('signature-error').hidden=false;scheduleSave();});
function validate(){
 if(!selectedRoute){status('Choose a country and two different branches.');return false;}
 if(!productsReady){status('Product data is not ready. Please reload after checking products.csv.');return false;}
 const active=[...$('item-rows').rows].filter(rowHasData);if(!active.length){status('Enter at least one item.');return false;}
 $('prepared').setCustomValidity($('prepared').value.trim()?'':'Enter your name.');if(!$('prepared').reportValidity())return false;
 for(const row of active){applyProduct(row,false);for(const input of row.querySelectorAll('input,textarea')){input.setCustomValidity(input.name==='uom'&&!productUoms.includes(input.value)?'Choose a UOM from the product list.':input.required&&!input.value.trim()?input.name==='batch'?'Batch is required for this product.':'Please complete this field.':input.name==='batch'&&input.value&&(input.value.length<6||input.value.length>17)?'Batch must contain 6-17 characters.':'');if(input.name==='barcode')checkBarcode(input,true);if(!input.checkValidity()){input.reportValidity();return false;}}}
 if(!TransferRules.hasSignature(signature)){canvas.classList.add('signature-missing');$('signature-error').hidden=false;canvas.focus();status('Draw your signature before downloading.');return false;}
 return true;
}

let fontkitLoading;
async function loadArabicPdfSupport(data){if(!(/[\u0600-\u06ff]/.test(JSON.stringify(data))||data.language==='ar')||window.fontkit)return;if(!fontkitLoading)fontkitLoading=new Promise((resolve,reject)=>{const script=document.createElement('script');script.src='vendor/fontkit.umd.min.js';script.onload=resolve;script.onerror=()=>{script.remove();fontkitLoading=null;reject(new Error('Arabic font support could not be loaded. Please try again.'));};document.head.append(script);});await fontkitLoading;}
async function downloadPDF(){if(!validate())return;clearTimeout(saveTimer);const buttons=[$('print-button'),$('print-bottom')];buttons.forEach(b=>b.disabled=true);try{const data=structuredClone(snapshot());data.version=nextVersion(data.reference);data.id=crypto.randomUUID();await loadArabicPdfSupport(data);const bytes=await TransferPDF.createTransferPDF(data),url=URL.createObjectURL(new Blob([bytes],{type:'application/pdf'})),a=document.createElement('a');a.href=url;a.download=data.reference.replace(/[^A-Za-z0-9_-]/g,'_')+'_v'+data.version+'.pdf';document.body.append(a);a.click();a.remove();saveDownload(data);setTimeout(()=>URL.revokeObjectURL(url),60000);status('Version '+data.version+' downloaded. Attach this PDF to your email.');}catch(e){status('PDF could not be created: '+e.message);}finally{buttons.forEach(b=>b.disabled=!selectedRoute);}}
$('print-button').addEventListener('click',downloadPDF);$('print-bottom').addEventListener('click',downloadPDF);
function showPage(){const t=location.hash==='#transfer';$('home').hidden=t;$('transfer').hidden=!t;document.title=t?'Transfer request · Inventory Department':'Inventory Department · Branch Operations';}window.addEventListener('hashchange',showPage);newIdentity();addRow();showPage();
(async()=>{try{const response=await fetch('TRANSFER_CONF.csv',{cache:'no-cache'});if(!response.ok)throw new Error('HTTP '+response.status);const bytes=await response.arrayBuffer();let text;try{text=new TextDecoder('utf-8',{fatal:true}).decode(bytes);}catch(_){text=new TextDecoder('windows-1252').decode(bytes);}routes=TransferCSV.readRoutes(text);$('country').replaceChildren(new Option('Select country',''));sorted(routes.map(r=>r.country)).forEach(c=>$('country').add(new Option(c,c)));$('country').disabled=false;try{const s=JSON.parse(localStorage.getItem(memoryKey)||'null');if(s&&routes.some(r=>r.country===s.country)){$('country').value=s.country;setCountry();setSource(s.from);chosenTo=destinationBranches.includes(s.to)?s.to:'';$('to').value=chosenTo;$('to').setCustomValidity(chosenTo?'':'Choose a destination branch.');setDestination(s.code);}}catch(_){}try{const saved=JSON.parse(localStorage.getItem(formsKey)||'[]');savedForms=Array.isArray(saved)?saved.filter(s=>s&&typeof s.id==='string'&&typeof s.referenceSuffix==='string'&&Array.isArray(s.items)).slice(0,10):[];}catch(_){savedForms=[];}renderSaved();$('data-status').textContent='Choose branches, enter items, then sign and download. Your branch selections are remembered.';}catch(e){$('data-status').classList.add('error');$('data-status').textContent='Branch data could not be loaded. '+e.message;}})();
function selectContents(e){const field=e.target;if(field.matches('input,textarea')&&!field.readOnly&&!field.disabled){try{field.select();}catch(_){}}}
$('transfer-form').addEventListener('focusin',selectContents);
$('transfer-form').addEventListener('pointerup',selectContents);

(async()=>{try{const response=await fetch('products.csv',{cache:'no-cache'});if(!response.ok)throw new Error('HTTP '+response.status);const bytes=await response.arrayBuffer();let text;try{text=new TextDecoder('utf-8',{fatal:true}).decode(bytes);}catch(_){text=new TextDecoder('windows-1252').decode(bytes);}const catalog=InventoryProducts.readProducts(text);products=catalog.products;productUpcs=catalog.upcs;productUoms=catalog.uoms;uoms.replaceChildren();productUoms.forEach(v=>uoms.append(new Option(v,v)));productsReady=true;[...$('item-rows').rows].forEach(row=>{applyBarcode(row,true);checkBarcode(row.querySelector("[name=barcode]"),false);});$('product-status').textContent='Product names, UOMs and batch rules are ready.';}catch(e){$('product-status').textContent='Product data could not be loaded: '+e.message;$('product-status').classList.add('error');}})();

$('excel-download').addEventListener('click',()=>{if(!validate())return;const data=snapshot(),bytes=TransferExcel.createWorkbook(data),url=URL.createObjectURL(new Blob([bytes],{type:'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'})),a=document.createElement('a');a.href=url;a.download=data.reference.replace(/[^A-Za-z0-9_-]/g,'_')+'_items.xlsx';document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),60000);status('Excel downloaded with one item per row and separate columns. Send it with the signed PDF.');});
