(function(root){
 'use strict';
 async function createPDF(data,lib,assets){const {PDFDocument,StandardFonts,rgb}=lib||root.PDFLib,doc=await PDFDocument.create(),normal=await doc.embedFont(StandardFonts.Helvetica),bold=await doc.embedFont(StandardFonts.HelveticaBold),i18n=typeof module!=='undefined'&&module.exports?require('./language.js'):root.InventoryI18n,h=t=>i18n.header(t,data.language),blue=rgb(.08,.28,.44),light=rgb(.9,.94,.97),white=rgb(1,1,1),black=rgb(0,0,0);let arabic;
 if(data.language==='ar'||/[\u0600-\u06ff]/.test(JSON.stringify(data))){const bytes=assets?.fontBytes||new Uint8Array(await (await fetch('vendor/fonts/Arabic-Regular.ttf')).arrayBuffer()),kit=assets?.fontkit||root.fontkit;if(!kit)throw new Error('Arabic font support is unavailable.');doc.registerFontkit(kit);arabic=await doc.embedFont(bytes,{subset:true});}
 const font=(value,heavy)=>/[\u0600-\u06ff]/.test(value)?arabic:heavy?bold:normal,items=data.items;
 const pages=Math.max(1,Math.ceil(items.length/22));for(let n=0;n<pages;n++){const page=doc.addPage([595.28,841.89]);let y=812;
 function cell(value,x,top,width,height,heavy=false,fill=null,size=9){const text=String(value??''),f=font(text,heavy);if(fill)page.drawRectangle({x,y:top-height,width,height,color:fill});page.drawRectangle({x,y:top-height,width,height,borderColor:black,borderWidth:.5});let fitted=size;while(f.widthOfTextAtSize(text,fitted)>width-8&&fitted>6)fitted-=.2;const lines=[];let line='';for(const c of text){if(f.widthOfTextAtSize(line+c,fitted)>width-8&&line){lines.push(line);line='';}line+=c;}if(line)lines.push(line);if(lines.length*(fitted+2)>height-6)throw new Error('This field is too long for the report: '+text);lines.forEach((s,i)=>page.drawText(s,{x:/[\u0600-\u06ff]/.test(s)?x+width-4-f.widthOfTextAtSize(s,fitted):x+4,y:top-6-fitted-i*(fitted+2),font:f,size:fitted,color:fill===blue?white:black}));}
 cell(h('BRANCH SAMPLE / CONSUMPTION REPORT'),28,y,539,30,true,blue,15);y-=30;cell(h('Branch'),28,y,100,30,true,light,10);cell(data.branch,128,y,439,30,true,light,12);y-=30;cell(h('Transaction Num'),28,y,100,25,true,light,9);cell(data.reference+(data.version?' / v'+data.version:''),128,y,439,25,true,light,10);y-=25;cell(h('From date'),28,y,100,25,true);cell(data.start,128,y,169.5,25,true);cell(h('To date'),297.5,y,100,25,true);cell(data.end,397.5,y,169.5,25,true);y-=25;
 if(data.profile?.entity){cell(h('LEGAL ENTITY'),28,y,100,25,true);cell(data.profile.entity,128,y,439,25,true);y-=25;}
 const cols=[62,100,190,64,60,63],headers=['ITEM CODE','BATCH BARCODE','ITEM NAME','QTY USED','UNIT','Reason'];let x=28;headers.forEach((v,i)=>{cell(h(v),x,y,cols[i],26,true,blue,8);x+=cols[i];});y-=26;
 for(let row=0;row<22;row++){const i=items[n*22+row],values=i?[i.code,i.barcode||i.batch||'',i.name,Number(i.quantity).toFixed(3),i.uom,i.reason]:['','','','','',''];x=28;values.forEach((v,j)=>{cell(v,x,y,cols[j],22,false,null,8);x+=cols[j];});y-=22;}
 y-=17;cell(h('Prepared and sent by'),28,y,110,22,true,light,8);cell(data.prepared,138,y,159.5,22);cell(h('Received by'),297.5,y,90,22,true,light,8);cell(data.received||'',387.5,y,179.5,22);y-=27;for(const s of data.signature||[])for(let k=1;k<s.length;k++)page.drawLine({start:{x:32+s[k-1][0]*230,y:y-s[k-1][1]*40},end:{x:32+s[k][0]*230,y:y-s[k][1]*40},thickness:1,color:blue});page.drawLine({start:{x:28,y:y-44},end:{x:280,y:y-44},thickness:.5,color:black});let footerX=28;for(const v of [h('Page'),String(n+1),h('of'),String(pages)]){const f=font(v,false);page.drawText(v,{x:footerX,y:22,size:8,font:f,color:black});footerX+=f.widthOfTextAtSize(v,8)+7;}
 }
 const excel=typeof module!=='undefined'&&module.exports?require('./excel.js'):root.TransferExcel;if(excel)await doc.attach(excel.createWorkbook(data),'Items.xlsx',{mimeType:'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',description:'Sample and consumption item rows'});doc.setTitle('Branch Sample / Consumption '+data.reference);return doc.save();
 }
 const api={createPDF};if(typeof module!=='undefined'&&module.exports)module.exports=api;else root.ConsumptionPDF=api;
})(typeof globalThis!=='undefined'?globalThis:this);
