(function(){
 'use strict';const el=id=>document.getElementById('sc-'+id),key='inventory.consumption.versions.v1',memory='inventory.consumption.branch.v1';let branch='',choices=[],strokes=[],stroke=null,pointer=null,versions=[],reference='',draftTimer,restoring=false;
 function message(text){el('status').textContent=text;}
 function identity(){const date=new Date(),parts=new Intl.DateTimeFormat('en-GB',{timeZone:'Asia/Dubai',year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',second:'2-digit',hourCycle:'h23'}).formatToParts(date),get=t=>parts.find(p=>p.type===t).value;reference='SC '+get('day')+get('month')+get('year')+'-'+get('hour')+get('minute')+get('second')+'-'+crypto.randomUUID().slice(0,4);el('reference').value=reference;el('start').value=el('end').value=get('year')+'-'+get('month')+'-'+get('day');}
 function country(){choices=sorted(routes.filter(r=>r.country===el('country').value).flatMap(r=>[r.from,r.to]));el('branch').disabled=!choices.length;branch='';el('branch').value='';pick('');}
 function pick(value){branch=choices.includes(value)?value:'';el('branch').setCustomValidity(branch?'':'Choose a branch from the results.');const profile=TransferRules.branchProfile(routes,el('country').value,branch);el('entity').textContent=profile?.entity||'';el('warehouse').textContent=profile?.warehouse||'';try{if(branch)localStorage.setItem(memory,JSON.stringify({country:el('country').value,branch}));}catch(_){} }
 search(el('branch'),el('results'),()=>choices,pick,saveDraft);el('country').addEventListener('change',country);
 function values(row){return Object.fromEntries([...row.querySelectorAll('input,textarea,select')].map(f=>[f.name,f.value.trim()]));}
 function filled(row){const v=values(row);return Object.entries(v).some(([k,v])=>k!=='reason'&&v);}
 function spare(){const rows=el('rows').rows;if(!rows.length||filled(rows[rows.length-1]))add();[...rows].forEach((r,i)=>r.cells[0].textContent=i+1);}
 function add(data={}){const row=el('rows').insertRow();row.insertCell();for(const [name,label]of [['barcode','Barcode'],['code','Item code'],['batch','Batch'],['name','Item name'],['uom','UOM'],['quantity','Qty used'],['reason','Reason']]){const f=document.createElement(name==='reason'?'select':['name','batch'].includes(name)?'textarea':'input');f.name=name;f.setAttribute('aria-label',label);f.required=['code','name','uom','quantity','reason'].includes(name);if(f.tagName==='INPUT')f.type=name==='quantity'?'number':'text';if(f.tagName==='TEXTAREA'){f.rows=1;f.maxLength=name==='batch'?17:150;}if(name==='quantity'){f.min='.001';f.step='.001';}if(name==='code'){f.pattern='[0-9]{6}';f.maxLength=6;f.inputMode='numeric';}if(name==='barcode'){f.pattern='[0-9]+';f.inputMode='numeric';f.maxLength=80;}if(name==='uom')f.setAttribute('list','uom-options');if(name==='reason')for(const v of ['SAMPLE','CONSUMPTION'])f.add(new Option(v,v));f.value=data[name]||(name==='reason'?'SAMPLE':'');const cell=row.insertCell();cell.dataset.label=label;cell.append(f);
  f.addEventListener('input',()=>{if(name==='barcode'){applyBarcode(row);checkBarcode(f,false);}if(name==='code')applyProduct(row);if(name==='uom')f.setCustomValidity(productUoms.includes(f.value)?'':'Choose a unit from the product list.');else if(name!=='barcode')f.setCustomValidity('');spare();});
  if(name==='barcode'){f.addEventListener('blur',()=>checkBarcode(f,true));f.addEventListener('keydown',e=>{if(['Enter','Tab'].includes(e.key)){if(!checkBarcode(f,true)){e.preventDefault();f.reportValidity();}else if(e.key==='Enter'){e.preventDefault();row.querySelector('[name=quantity]').focus();}}});}
  if(name==='quantity')f.addEventListener('keydown',e=>{if(e.key==='Enter'){e.preventDefault();spare();row.nextElementSibling?.querySelector('[name=barcode]').focus();}});
 }
 const remove=document.createElement('button');remove.type='button';remove.className='remove-row';remove.textContent='×';remove.setAttribute('aria-label','Remove item');remove.addEventListener('click',()=>{row.remove();spare();saveDraft();});row.insertCell().append(remove);applyBarcode(row,false);InventoryI18n.apply(row);return row;}
 function snapshot(){return {formType:'consumption',language:InventoryI18n.language(),reference,country:el('country').value,branch,profile:TransferRules.branchProfile(routes,el('country').value,branch),start:el('start').value,end:el('end').value,prepared:el('prepared').value.trim(),received:el('received').value.trim(),signature:structuredClone(strokes),items:[...el('rows').rows].filter(filled).map(values)};}
 function validate(){const scope=el('form');InventoryValidation.clear(scope);const extras=[],fields=[];if(!productsReady)extras.push('Product list is still loading.');el('country').setCustomValidity(el('country').value?'':'Choose a country.');el('branch').setCustomValidity(branch?'':'Choose a branch from the results.');el('end').setCustomValidity(el('end').value<el('start').value?'To date must be on or after From date.':'');el('prepared').setCustomValidity(el('prepared').value.trim()?'':'Enter your name.');for(const id of ['country','branch','start','end','prepared','received'])fields.push(el(id));if(!branch)extras.push('Choose your country and branch.');
 let active=[...el('rows').rows].filter(filled);if(!active.length){extras.push('Enter at least one item.');active=[el('rows').rows[0]];}for(const row of active.filter(Boolean)){applyProduct(row,false);for(const f of row.querySelectorAll('input,textarea,select')){f.setCustomValidity(f.name==='uom'&&!productUoms.includes(f.value)?'Choose a unit from the product list.':f.name==='batch'&&f.value&&(f.value.length<6||f.value.length>17)?'Batch must contain 6-17 characters.':f.required&&!f.value.trim()?'Complete this field.':'');if(f.name==='barcode')checkBarcode(f,true);fields.push(f);}}
 const signed=TransferRules.hasSignature(strokes);canvas.classList.toggle('signature-missing',!signed);canvas.setAttribute('aria-invalid',String(!signed));let hint=el('signature-error');if(!hint){hint=document.createElement('p');hint.id='sc-signature-error';hint.className='field-error';hint.setAttribute('role','alert');canvas.insertAdjacentElement('afterend',hint);}hint.hidden=signed;hint.textContent='Signature required before download.';if(!signed)extras.push('Draw your signature before downloading.');const result=InventoryValidation.finish(scope,fields,extras);if(!result.valid){message(result.message);if(result.first){result.first.focus();result.first.reportValidity();}else if(!signed)canvas.focus();}else message('All required fields are complete.');return result.valid;}

 const canvas=el('signature'),ctx=canvas.getContext('2d');function draw(){ctx.clearRect(0,0,900,300);ctx.strokeStyle='#095c78';ctx.lineWidth=4;ctx.lineCap='round';for(const s of strokes){if(!s.length)continue;ctx.beginPath();ctx.moveTo(s[0][0]*900,s[0][1]*300);for(const p of s.slice(1))ctx.lineTo(p[0]*900,p[1]*300);ctx.stroke();}}
 function point(e){const b=canvas.getBoundingClientRect();return [Math.max(0,Math.min(1,(e.clientX-b.left)/b.width)),Math.max(0,Math.min(1,(e.clientY-b.top)/b.height))];}canvas.addEventListener('pointerdown',e=>{if(pointer!==null)return;e.preventDefault();pointer=e.pointerId;canvas.setPointerCapture(pointer);stroke=[point(e)];strokes.push(stroke);canvas.classList.remove('signature-missing');draw();});canvas.addEventListener('pointermove',e=>{if(e.pointerId===pointer&&stroke){stroke.push(point(e));draw();}});for(const type of ['pointerup','pointercancel','lostpointercapture'])canvas.addEventListener(type,e=>{if(e.pointerId===pointer){pointer=null;stroke=null;saveDraft();}});el('clear').addEventListener('click',()=>{strokes=[];draw();saveDraft();});
 function render(){el('saved').replaceChildren();versions.forEach(data=>{const b=document.createElement('button');b.className='saved-form';b.type='button';const title=document.createElement('strong'),info=document.createElement('span');title.textContent=data.reference+(data.version?' / v'+data.version:' / Draft');info.textContent=data.branch+' · '+data.items.length+' items';b.append(title,info);b.addEventListener('click',()=>restore(data));el('saved').append(b);});}
 function restore(data){restoring=true;reference=data.reference;el('reference').value=reference;el('country').value=data.country;country();el('branch').value=data.branch;pick(data.branch);el('start').value=data.start;el('end').value=data.end;el('prepared').value=data.prepared;el('received').value=data.received||'';el('rows').replaceChildren();data.items.forEach(add);spare();strokes=structuredClone(data.signature||[]);draw();restoring=false;message('Saved form opened. Edit it and download a new version.');}
 function persist(){try{localStorage.setItem(key,JSON.stringify(versions));render();}catch(_){message('Browser storage is full. Keep your downloaded files.');}}
 function saveDraft(){if(restoring)return;clearTimeout(draftTimer);draftTimer=setTimeout(()=>{const data=snapshot();if(!data.branch&&!data.items.length)return;versions=[data,...versions.filter(v=>v.reference!==reference||v.version)].slice(0,10);persist();},500);}
 function download(bytes,name,mime){const url=URL.createObjectURL(new Blob([bytes],{type:mime})),a=document.createElement('a');a.href=url;a.download=name;document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),60000);}
 async function pdf(){if(!validate())return;const buttons=[el('pdf'),el('pdf-bottom')];buttons.forEach(b=>b.disabled=true);clearTimeout(draftTimer);try{const data=snapshot(),counterKey=key+'.counters';let counters={};try{counters=JSON.parse(localStorage.getItem(counterKey)||'{}');}catch(_){}data.version=Math.max(Number(counters[reference])||0,...versions.filter(v=>v.reference===reference).map(v=>v.version||0))+1;await loadArabicPdfSupport(data);const bytes=await ConsumptionPDF.createPDF(data);download(bytes,reference.replace(/[^A-Za-z0-9_-]/g,'_')+'_v'+data.version+'.pdf','application/pdf');versions=[data,...versions.filter(v=>v.reference!==reference||v.version)].slice(0,10);counters[reference]=data.version;try{localStorage.setItem(counterKey,JSON.stringify(counters));}catch(_){}persist();message('PDF version '+data.version+' downloaded.');}catch(e){message('Could not download PDF: '+e.message);}finally{buttons.forEach(b=>b.disabled=false);}}
 for(const id of ['pdf','pdf-bottom'])el(id).addEventListener('click',pdf);el('excel').addEventListener('click',()=>{if(validate())download(TransferExcel.createWorkbook(snapshot()),reference.replace(/[^A-Za-z0-9_-]/g,'_')+'_items.xlsx','application/vnd.openxmlformats-officedocument.spreadsheetml.sheet');});for(const id of ['add','add-bottom'])el(id).addEventListener('click',()=>{add().querySelector('input').focus();});el('form').addEventListener('submit',e=>e.preventDefault());el('form').addEventListener('input',saveDraft);el('form').addEventListener('change',saveDraft);
 el('new').addEventListener('click',()=>{clearTimeout(draftTimer);identity();el('rows').replaceChildren();add();el('prepared').value=el('received').value='';strokes=[];draw();message('New report ready.');});
 function page(){el('country');document.getElementById('consumption').hidden=location.hash!=='#consumption';if(location.hash==='#consumption')document.title='Sample / Consumption · Inventory Department';}window.addEventListener('hashchange',page);identity();add();page();
 // The shared loaders dispatch this event when the same CSV data is ready.
 function ready(){if(!routes.length||!productsReady)return;el('country').replaceChildren(new Option('Select country',''));sorted(routes.map(r=>r.country)).forEach(c=>el('country').add(new Option(c,c)));el('country').disabled=false;try{const data=JSON.parse(localStorage.getItem(memory)||'null');if(data&&routes.some(r=>r.country===data.country)){el('country').value=data.country;country();el('branch').value=data.branch;pick(data.branch);}}catch(_){}try{const data=JSON.parse(localStorage.getItem(key)||'[]');versions=Array.isArray(data)?data.filter(v=>v.formType==='consumption'&&typeof v.reference==='string'&&Array.isArray(v.items)).slice(0,10):[];}catch(_){}render();}
 window.addEventListener('inventory-data-ready',ready);ready();window.ConsumptionForm={snapshot,validate,restore};
})();
