(function(root){
 'use strict';
 const encode=s=>new TextEncoder().encode(s);
 const xml=s=>String(s??'').replace(/[\u0000-\u0008\u000b\u000c\u000e-\u001f]/g,'').replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;');
 function crc(bytes){let n=0xffffffff;for(const b of bytes){n^=b;for(let i=0;i<8;i++)n=(n>>>1)^((n&1)?0xedb88320:0);}return(n^0xffffffff)>>>0;}
 function zip(files){const chunks=[],directory=[];let offset=0;const header=(length)=>new Uint8Array(length),u16=(b,p,v)=>new DataView(b.buffer).setUint16(p,v,true),u32=(b,p,v)=>new DataView(b.buffer).setUint32(p,v,true);
  for(const [path,content]of files){const name=encode(path),data=encode(content),sum=crc(data),local=header(30+name.length);u32(local,0,0x04034b50);u16(local,4,20);u16(local,12,33);u32(local,14,sum);u32(local,18,data.length);u32(local,22,data.length);u16(local,26,name.length);local.set(name,30);chunks.push(local,data);
   const central=header(46+name.length);u32(central,0,0x02014b50);u16(central,4,20);u16(central,6,20);u16(central,14,33);u32(central,16,sum);u32(central,20,data.length);u32(central,24,data.length);u16(central,28,name.length);u32(central,42,offset);central.set(name,46);directory.push(central);offset+=local.length+data.length;}
  const size=directory.reduce((n,b)=>n+b.length,0),end=header(22);u32(end,0,0x06054b50);u16(end,8,files.length);u16(end,10,files.length);u32(end,12,size);u32(end,16,offset);chunks.push(...directory,end);const output=new Uint8Array(offset+size+22);let pos=0;for(const b of chunks){output.set(b,pos);pos+=b.length;}return output;
 }
 function worksheet(rows,widths,filter){const columns=widths.map((w,i)=>`<col min="${i+1}" max="${i+1}" width="${w}" customWidth="1"/>`).join('');const body=rows.map((row,i)=>`<row r="${i+1}">${row.map((value,j)=>{const ref=String.fromCharCode(65+j)+(i+1);return typeof value==='number'&&Number.isFinite(value)?`<c r="${ref}"><v>${value}</v></c>`:`<c r="${ref}" t="inlineStr"><is><t xml:space="preserve">${xml(value)}</t></is></c>`;}).join('')}</row>`).join('');return `<?xml version="1.0" encoding="UTF-8"?><worksheet xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main"><sheetViews><sheetView workbookViewId="0"><pane ySplit="1" topLeftCell="A2" activePane="bottomLeft" state="frozen"/></sheetView></sheetViews><cols>${columns}</cols><sheetData>${body}</sheetData>${filter?`<autoFilter ref="A1:H${rows.length}"/>`:''}</worksheet>`;}
 function createWorkbook(data){const consumption=data.formType==='consumption';const items=consumption?[['SR Num','ITEM CODE','BATCH BARCODE','ITEM NAME','QTY USED','UNIT','Reason'],...data.items.map((i,n)=>[n+1,i.code,i.barcode||i.batch||'',i.name,Number(i.quantity),i.uom,i.reason])]:[['#','4 BARCODE','ITEM CODE','3 BARCODE','BATCH','ITEM NAME','UOM','QUANTITY'],...data.items.map((i,n)=>[n+1,i.barcode4||'',i.code||'',i.barcode3||'',i.batch||'',i.name||'',i.uom||'',Number(i.quantity)])];const route=data.route||{},details=data.details||{};const info=[['Field','Value'],['Reference',data.reference],['Version',data.version||'Draft'],['Date',data.date],['Country',data.country||route.country],['Transfer from',data.from||route.from],['Transfer to',data.to||route.to],['From legal entity',route.fromEntity],['To legal entity',route.toEntity],['Type',details.type],['Reason',data.reason],['Prepared by',data.prepared],['Received by',data.received]];if(consumption)info.push(['Branch',data.branch],['From date',data.start],['To date',data.end],['Legal entity',data.profile?.entity||'']);
 return zip([
 ['[Content_Types].xml','<Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types"><Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/><Default Extension="xml" ContentType="application/xml"/><Override PartName="/xl/workbook.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet.main+xml"/><Override PartName="/xl/worksheets/sheet1.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.worksheet+xml"/><Override PartName="/xl/worksheets/sheet2.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.worksheet+xml"/></Types>'],
 ['_rels/.rels','<Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument" Target="xl/workbook.xml"/></Relationships>'],
 ['xl/workbook.xml','<workbook xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main" xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships"><sheets><sheet name="Items" sheetId="1" r:id="rId1"/><sheet name="Transfer details" sheetId="2" r:id="rId2"/></sheets></workbook>'],
 ['xl/_rels/workbook.xml.rels','<Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/worksheet" Target="worksheets/sheet1.xml"/><Relationship Id="rId2" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/worksheet" Target="worksheets/sheet2.xml"/></Relationships>'],
 ['xl/worksheets/sheet1.xml',worksheet(items,consumption?[10,14,22,55,14,16,20]:[6,20,14,20,22,55,16,14],!consumption)],['xl/worksheets/sheet2.xml',worksheet(info,[24,65],false)]
 ]);}
 const api={createWorkbook};if(typeof module!=='undefined'&&module.exports)module.exports=api;else root.TransferExcel=api;
})(typeof globalThis!=='undefined'?globalThis:this);
