const fs=require('fs'),assert=require('node:assert/strict'),{JSDOM}=require('../tmp/test-runtime/node_modules/jsdom');
const dom=new JSDOM(fs.readFileSync('index.html','utf8'),{url:'https://inventory.test/#consumption',runScripts:'outside-only'}),w=dom.window,d=w.document;w.TextDecoder=TextDecoder;w.TextEncoder=TextEncoder;w.structuredClone=structuredClone;w.HTMLCanvasElement.prototype.getContext=()=>({clearRect(){},beginPath(){},moveTo(){},lineTo(){},stroke(){}});w.HTMLCanvasElement.prototype.setPointerCapture=()=>{};w.HTMLCanvasElement.prototype.getBoundingClientRect=()=>({left:0,top:0,width:900,height:300});w.fetch=async url=>{const b=fs.readFileSync(url);return{ok:true,arrayBuffer:async()=>b.buffer.slice(b.byteOffset,b.byteOffset+b.byteLength)};};
w.eval(['csv.js','rules.js','products.js','language.js','validation.js','app.js','consumption.js'].map(f=>fs.readFileSync(f,'utf8')).join('\n'));
const el=id=>d.getElementById('sc-'+id),field=name=>el('rows').rows[0].querySelector('[name='+name+']'),input=(name,value)=>{field(name).value=value;field(name).dispatchEvent(new w.Event('input',{bubbles:true}));};
(async()=>{try{await new Promise(setImmediate);assert.equal(d.getElementById('home').hidden,true);assert.equal(d.getElementById('transfer').hidden,true);assert.equal(d.getElementById('consumption').hidden,false);el('country').value='UAE';el('country').dispatchEvent(new w.Event('change'));el('branch').value='216 - Chocola Pure Al Hamra';el('branch').dispatchEvent(new w.Event('input'));assert.match(el('entity').textContent,/46697/);el('pdf').click();for(const name of ['code','name','uom','quantity'])assert.ok(field(name).classList.contains('validation-invalid'));assert.ok(el('prepared').classList.contains('validation-invalid'));assert.ok(el('signature').classList.contains('signature-missing'));el('pdf').click();assert.equal(d.querySelectorAll('#sc-form .validation-error').length,5);
input('barcode','4117588148970');assert.equal(field('code').value,'117588');assert.equal(field('name').value,'ROASTED BEANS COLOMBIA');assert.equal(field('batch').readOnly,true);assert.equal(el('rows').rows.length,2);assert.equal(field('reason').value,'SAMPLE');input('reason','CONSUMPTION');el('prepared').value='Test preparer';assert.equal(w.ConsumptionForm.validate(),false,'signature required');
const canvas=el('signature');for(const [type,x,y]of [['pointerdown',30,20],['pointermove',240,100],['pointerup',240,100]]){const e=new w.MouseEvent(type,{clientX:x,clientY:y});Object.defineProperty(e,'pointerId',{value:1});canvas.dispatchEvent(e);}assert.equal(w.ConsumptionForm.validate(),true);assert.equal(w.ConsumptionForm.snapshot().items.length,1);
el('end').value='2000-01-01';assert.equal(w.ConsumptionForm.validate(),false);el('end').value=el('start').value;input('barcode','3117474148970');assert.equal(field('batch').required,true);assert.equal(w.ConsumptionForm.validate(),false);input('batch','ABC123');assert.equal(w.ConsumptionForm.validate(),true);const saved=w.ConsumptionForm.snapshot();w.ConsumptionForm.restore(saved);assert.equal(field('batch').value,'ABC123');assert.equal(field('reason').value,'CONSUMPTION');assert.equal(w.ConsumptionForm.validate(),true);input('barcode','311747414897');field('barcode').dispatchEvent(new w.Event('blur'));assert.equal(field('barcode').checkValidity(),false);
const {createPDF}=require('../consumption-pdf.js'),lib=require('../vendor/pdf-lib.min.js');saved.version=1;saved.items=Array.from({length:23},()=>saved.items[0]);const bytes=await createPDF(saved,lib);assert.equal((await lib.PDFDocument.load(bytes)).getPageCount(),2);fs.writeFileSync('tmp/pdfs/consumption-test.pdf',bytes);const assets={fontBytes:fs.readFileSync('vendor/fonts/Arabic-Regular.ttf'),fontkit:require('../vendor/fontkit.umd.min.js')};await createPDF({...saved,language:'ar'},lib,assets).then(b=>fs.writeFileSync('tmp/pdfs/consumption-arabic-test.pdf',b));console.log('Consumption tests passed: branch data, shared product lookup, barcode/batch rules, automatic rows, reasons, dates, required signature, restore and 23-item bilingual PDF.');}finally{w.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
